### ISSUE TITLE
C Merge Checklist

### ISSUE THREAD

**Issue by brandtbucher** [InvestmentSystems/static-frame#55]
### On the `c` branch:
- [X] Update `setup.py` with `name="static-frame"` (it's currently "C-SF", for testing).
- [X] Update `.travis.yml` to deploy off of the `master` branch.
- [X] Update `.travis.yml` to use the "real" PyPI.
- [ ] Update `.travis.yml` with @flexatone's PyPI credentials (see me for this).
- [ ] Optionally, update `.travis.yml` to deploy to PyPI only on tags. I'd rather just deploy whenever the version changes in `setup.py` (which is what it does now), but we can chat about that.

### On the `master` branch:
- [ ] Make a new minor release. 
- [ ] Merge `c`.
- [ ] Use dev releases to make the necessary changes to our conda-forge recipe. This will be the last tricky part, but I'm pretty sure I've figured it out!

**Comment by flexatone** [comment]
Excellent plan. Lets chat about the pending details.

**Comment by flexatone** [comment]
I  will want to wait a few more minor releases before merging in the C extensions, as I am finding lots of little issues with the new property tests that need to be fixed, and some of those fixes involve the low-level functions in util.py. Further, with extensive property tests, implementation and testing of those extensions will be improved.

**Comment by brandtbucher** [comment]
I agree... I'll keep it in sync with changes in the meantime.

**Comment by flexatone** [comment]
Our C extensions have moved to a new project, from which we will continue their development.

https://github.com/InvestmentSystems/arraykit
